<div style="display:block; margin:{{ margin|default('0')}};">
<ins class="adsbygoogle"
    style="display:block"
    data-ad-format="{{ format|default('auto') }}"
    data-ad-layout-key="{{ layout_key }}"
    data-ad-client="{{ client|default('ca-pub-9209957480256741') }}"
    data-ad-slot="{{ slot }}"
    data-full-width-responsive="{{ width_responsive|default(true) }}"></ins>
<script>
    (adsbygoogle = window.adsbygoogle || []).push({});
</script>
</div>
